[package]
name = "playlist-from-csv"
version = "0.1.0"
authors = ["Oliver O'Neill"]

[dependencies]
rspotify = "0.2.3"
failure = "0.1"
argparse = "0.2.1"
csv = "1.0"
serde_derive = "1.0"
serde = "1.0"
